# Generated by Django 4.2.1 on 2023-05-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_slug"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customer",
            new_name="Customers",
        ),
        migrations.AddIndex(
            model_name="customers",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="store_custo_last_na_2e448d_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="customers",
            table="store_customer",
        ),
    ]
