# Generated by Django 4.2.1 on 2023-05-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_rename_customers_customer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="phone_number",
            new_name="phone",
        ),
    ]
