# Generated by Django 4.2.1 on 2023-05-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_rename_phone_number_customer_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="birthdate",
            new_name="birth_date",
        ),
    ]
