# Generated by Django 4.2.1 on 2023-05-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_rename_birthdate_customer_birth_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["title"]},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="tittle",
            new_name="title",
        ),
    ]
