# Generated by Django 4.2.1 on 2023-05-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_customer_options_order_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promotion",
            options={"ordering": ["discount"]},
        ),
    ]
